### ISSUE TITLE
Use osmium::geom::Tile?

### ISSUE THREAD

**Issue by joto** [mapbox/osm-tiler#25]
Libosmium has a class `osmium::geom::Tile` that already does a lot of what is implemented in `osm-tiler/handler.hpp`.

**Comment by morganherlocker** [comment]
@joto do you have a link to the docs so we can do a comparison?

**Comment by joto** [comment]
Docs are somewhat incomplete: http://docs.osmcode.org/libosmium/master/structosmium_1_1geom_1_1Tile.html
