### ISSUE TITLE
build fails on Ubuntu

### ISSUE THREAD

**Issue by bradoyler** [mapbox/osm-tiler#26]
error is:
```sh
g++ osm-tiler.cpp -o osm-tiler -isystem./mason_packages/.link/include -L./mason_packages/.link/lib  -std=c++11 -fvisibility=hidden -g -Wall -Wextra -Wfloat-equal -Wundef -Wcast-align -Wwrite-strings -Wlong-long -Wmissing-declarations -Wredundant-decls -Wshadow -Woverloaded-virtual -O3 -DNDEBUG  -lz -lpthread -lboost_program_options -lboost_filesystem -lboost_system;
/tmp/ccNL9CFc.o: In function 
`boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/home/dev/projects/osm-tiler/./mason_packages/.link/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
/home/dev/projects/osm-tiler/./mason_packages/.link/include/boost/program_options/errors.hpp:373: undefined reference to 
`boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
```

I'm totally clueless with these dependencies. Wondering if I'm missing a required package

**Comment by geeknik** [comment]
On Ubuntu 16.04 LTS, I see quite a few messages about `basename: missing operand` when I run `bootstrap.sh`:

``./bootstrap.sh
Cloning into './.mason'...
remote: Counting objects: 15085, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 15085 (delta 19), reused 21 (delta 14), pack-reused 15041
Receiving objects: 100% (15085/15085), 3.03 MiB | 0 bytes/s, done.
Resolving deltas: 100% (6157/6157), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
basename: missing operand
Try 'basename --help' for more information.
* Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/rapidjson/1.0.2.tar.gz
* Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/libosmium/2.7.2.tar.gz
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
* Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/protozero/1.3.0.tar.gz
* Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/utfcpp/2.3.4.tar.gz
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
* Downloading binary package https://mason-binaries.s3.amazonaws.com/linux-x86_64/boost_libfilesystem/1.61.0.tar.gz
* Downloading binary package https://mason-binaries.s3.amazonaws.com/linux-x86_64/boost_libprogram_options/1.61.0.tar.gz
* Downloading binary package https://mason-binaries.s3.amazonaws.com/headers/boost/1.61.0.tar.gz
* Linking zlib system dynamically
* Downloading binary package https://mason-binaries.s3.amazonaws.com/linux-x86_64/boost_libsystem/1.61.0.tar.gz
* Wrote configuration file /root/osm-tiler/mason_packages/linux-x86_64/zlib/system/mason.ini:
name=zlib
version=system
platform=linux
platform_version=x86_64
include_dirs={prefix}/include
ldflags=-L{prefix}/lib -lz
* Installed system-provided zlib 1.2.8
* Linking /root/osm-tiler/mason_packages/linux-x86_64/zlib/system
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Done linking /root/osm-tiler/mason_packages/linux-x86_64/zlib/system
* Installed binary package at /root/osm-tiler/mason_packages/headers/rapidjson/1.0.2
* Linking /root/osm-tiler/mason_packages/headers/rapidjson/1.0.2
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Installed binary package at /root/osm-tiler/mason_packages/linux-x86_64/boost_libfilesystem/1.61.0
* Installed binary package at /root/osm-tiler/mason_packages/headers/utfcpp/2.3.4
* Installed binary package at /root/osm-tiler/mason_packages/linux-x86_64/boost_libsystem/1.61.0
* Installed binary package at /root/osm-tiler/mason_packages/linux-x86_64/boost_libprogram_options/1.61.0
basename: missing operand
Try 'basename --help' for more information.
* Done linking /root/osm-tiler/mason_packages/headers/rapidjson/1.0.2
basename: missing operand
Try 'basename --help' for more information.
* Installed binary package at /root/osm-tiler/mason_packages/headers/protozero/1.3.0
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
* Linking /root/osm-tiler/mason_packages/linux-x86_64/boost_libfilesystem/1.61.0
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
* Linking /root/osm-tiler/mason_packages/headers/utfcpp/2.3.4
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Done linking /root/osm-tiler/mason_packages/linux-x86_64/boost_libfilesystem/1.61.0
* Linking /root/osm-tiler/mason_packages/linux-x86_64/boost_libprogram_options/1.61.0
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Linking /root/osm-tiler/mason_packages/linux-x86_64/boost_libsystem/1.61.0
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Done linking /root/osm-tiler/mason_packages/headers/utfcpp/2.3.4
* Done linking /root/osm-tiler/mason_packages/linux-x86_64/boost_libprogram_options/1.61.0
* Done linking /root/osm-tiler/mason_packages/linux-x86_64/boost_libsystem/1.61.0
* Linking /root/osm-tiler/mason_packages/headers/protozero/1.3.0
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Done linking /root/osm-tiler/mason_packages/headers/protozero/1.3.0
* Installed binary package at /root/osm-tiler/mason_packages/headers/libosmium/2.7.2
* Linking /root/osm-tiler/mason_packages/headers/libosmium/2.7.2
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Done linking /root/osm-tiler/mason_packages/headers/libosmium/2.7.2
* Installed binary package at /root/osm-tiler/mason_packages/headers/boost/1.61.0
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
* Linking /root/osm-tiler/mason_packages/headers/boost/1.61.0
* Links will be inside /root/osm-tiler/mason_packages/.link/
* Using bash fallback for symlinking (install lndir for faster symlinking)
* Done linking /root/osm-tiler/mason_packages/headers/boost/1.61.0
```

Once that is completed, I run `make -j4` and see this:
```
/tmp/ccqh1icF.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/tmp/ccqh1icF.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/detail/value_semantic.hpp:167: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/tmp/ccqh1icF.o: In function `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/detail/convert.hpp:79: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccqh1icF.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/detail/parsers.hpp:44: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/tmp/ccqh1icF.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccqh1icF.o: In function `boost::program_options::typed_value<unsigned int, char>::name() const':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccqh1icF.o: In function `main':
/root/osm-tiler/osm-tiler.cpp:20: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/tmp/ccqh1icF.o: In function `boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccqh1icF.o: In function `void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long)':
/root/osm-tiler/./mason_packages/.link/include/boost/program_options/detail/value_semantic.hpp:92: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost15program_options11typed_valueIjcEE[_ZTVN5boost15program_options11typed_valueIjcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/tmp/ccqh1icF.o:(.rodata._ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE[_ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'osm-tiler' failed
make: *** [osm-tiler] Error 1
```
